# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/build

# Include any dependencies generated for this target.
include src/CMakeFiles/hello.dir/depend.make

# Include the progress variables for this target.
include src/CMakeFiles/hello.dir/progress.make

# Include the compile flags for this target's objects.
include src/CMakeFiles/hello.dir/flags.make

src/CMakeFiles/hello.dir/main.cpp.o: src/CMakeFiles/hello.dir/flags.make
src/CMakeFiles/hello.dir/main.cpp.o: ../src/main.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object src/CMakeFiles/hello.dir/main.cpp.o"
	cd /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/build/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/hello.dir/main.cpp.o -c /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/src/main.cpp

src/CMakeFiles/hello.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/hello.dir/main.cpp.i"
	cd /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/build/src && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/src/main.cpp > CMakeFiles/hello.dir/main.cpp.i

src/CMakeFiles/hello.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/hello.dir/main.cpp.s"
	cd /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/build/src && /usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/src/main.cpp -o CMakeFiles/hello.dir/main.cpp.s

src/CMakeFiles/hello.dir/main.cpp.o.requires:

.PHONY : src/CMakeFiles/hello.dir/main.cpp.o.requires

src/CMakeFiles/hello.dir/main.cpp.o.provides: src/CMakeFiles/hello.dir/main.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/hello.dir/build.make src/CMakeFiles/hello.dir/main.cpp.o.provides.build
.PHONY : src/CMakeFiles/hello.dir/main.cpp.o.provides

src/CMakeFiles/hello.dir/main.cpp.o.provides.build: src/CMakeFiles/hello.dir/main.cpp.o


# Object files for target hello
hello_OBJECTS = \
"CMakeFiles/hello.dir/main.cpp.o"

# External object files for target hello
hello_EXTERNAL_OBJECTS =

src/hello: src/CMakeFiles/hello.dir/main.cpp.o
src/hello: src/CMakeFiles/hello.dir/build.make
src/hello: src/CMakeFiles/hello.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX executable hello"
	cd /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/build/src && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/hello.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
src/CMakeFiles/hello.dir/build: src/hello

.PHONY : src/CMakeFiles/hello.dir/build

src/CMakeFiles/hello.dir/requires: src/CMakeFiles/hello.dir/main.cpp.o.requires

.PHONY : src/CMakeFiles/hello.dir/requires

src/CMakeFiles/hello.dir/clean:
	cd /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/build/src && $(CMAKE_COMMAND) -P CMakeFiles/hello.dir/cmake_clean.cmake
.PHONY : src/CMakeFiles/hello.dir/clean

src/CMakeFiles/hello.dir/depend:
	cd /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/src /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/build /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/build/src /home/firefox66/Workspaces/C.C++.Tutor/firstCode/myCppTutor/build/src/CMakeFiles/hello.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : src/CMakeFiles/hello.dir/depend

